# Site settings
title: My test title
email: test-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Apparently, you have to reboot (ctrl -c + npm run watch) to update any changes made in this (config.yml) settings file.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  DidrikH

# Build settings
markdown: kramdown
